AppBundle\Entity\CollectionSlot:
    type: entity
    table: collectionslot
    repositoryClass: AppBundle\Repository\CollectionSlotRepository
    manyToOne:
        collection:
            targetEntity: Collection
            nullable: false
            inversedBy: slots
            joinColumn:
                name: collection_id
                referencedColumnName: id
        card:
            targetEntity: Card
            nullable: false
            joinColumn:
                name: card_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quantity:
            type: smallint
        dice:
            type: smallint
